### ISSUE TITLE
Virtual alias map does not get removed when removed from config

### ISSUE THREAD

**Issue by htgoebel** [debops/ansible-postfix#12]
I tried setting up a virtual alias map like this (see #11)

```
postfix_dependent_lists:
  virtual_alias_maps:
    - capability: 'null'
      list: [ 'hash:/etc/postfix/hash_tables/forward_all_to_admin' ]
```

Because the file does not exist, I wanted to remove this config option. But this failed, because this is stored in local facts.
Even adding

```
postfix_dependent_lists:
  virtual_alias_maps:
    - capability: 'null'
      list: []
```

did not remove the entry from main.cf. I had to remove the local facts.
