### ISSUE TITLE
Add Dovecot/SASL authentication

### ISSUE THREAD

**Issue by siretart** [debops/ansible-postfix#73]
I'd like to setup an MTA that authenticates against a dovecot instance that runs on the same host as dovecot.

 Documentation is here: http://wiki2.dovecot.org/HowTo/PostfixAndDovecotSASL

**Comment by muelli** [comment]
FTR: I think I got it working by putting smth like this in my `ansible/inventory/group_vars/debops_service_dovecot.yml`:

```
dovecot_auth_config_map:
    "service":
        unix_listener:
            "/var/spool/postfix/private/auth":
                mode: "0600"
                # Assuming the default Postfix user and group
                user: "postfix"
                group: "postfix"       


dovecot_auth_listeners:
    - "/var/spool/postfix/private/auth"

```

It would be nice if the integration was tighter, i.e. that this configuration would be used when `postfix_smtpd_sasl_type: dovecot`.
