### ISSUE TITLE
update documentation to reflect the requirement of a FQDN to be set

### ISSUE THREAD

**Issue by muelli** [debops/ansible-postfix#82]
currently the code seems to require that a FQDN is set:

```
- name: Override Postfix capabilities if FQDN is not set
  set_fact:
    postfix: [ 'local' ]
  when: ansible_domain is defined and not ansible_domain
```

However, the documentation does not mention that.

I'm not sure where to mention it, though. In any case, the example given in getting started seems to be wrong or at least not self-contained.
