### ISSUE TITLE
Error on running in custom playbook

### ISSUE THREAD

**Issue by computerlyrik** [debops/ansible-postfix#96]
I am running

```
  roles:
    - name: debops.postfix/env
      tags: [ 'role::postfix', 'role::secret', 'role::ferm' ]

    - name: debops.secret
      tags: [ 'role::secret', 'role::postfix' ]
      secret__directories:
        - '{{ postfix__secret__directories }}'

    - name: debops.postfix
      tags: [ 'role::postfix' ]
      vars:
.....
```

And getting the following error:

```
fatal: [myhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'iteritems'\n\nThe error appears to have been in '[parent_dir_omitted]ansible/roles/debops.postfix/env/tasks/main.yml': line 27, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    var: postfix__combined_mastercf\n- name: Prepare Postfix environment\n  ^ here\n"}
```

tracked it down to the line 1257 of ```defaults/main.yml```

```postfix__dependent_mastercf_filter``` seems to make the whole variable UNDEFINED

What am i doing wrong?

```
ansible --version                                                            :(
ansible 2.5.5
```
